# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

melt_dataframe <- function(data, id_vars_, measure_vars_, variable_name, value_name) {
    .Call('reshape2_melt_dataframe', PACKAGE = 'reshape2', data, id_vars_, measure_vars_, variable_name, value_name)
}

